### ISSUE TITLE
Remove numbers from morphology display

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#141]
@balmas said: This one is a little tricky.  The numbers allow us to find the right 
definition in lsj when there are multiple entries for a homonym, because 
the morpheus lemmas are directly drawn from the lsj entries.  They are 
less helpful for the other dictionaries though.

I think it needs to be addressed at some point, but will probably not do 
it in a patch release because I would be afraid of breaking things.
![uno-due](https://user-images.githubusercontent.com/41396793/47617953-9474b100-daa3-11e8-9912-cce647c089a0.JPG)
move number from 

https://github.com/alpheios-project/alpheios-core/issues/198

οὐδ'

**Comment by irina060981** [comment]
I believe that these issues are about the same theme -
https://github.com/alpheios-project/alpheios-core/issues/198

**Comment by balmas** [comment]
yes, related but I think #198 is a non-issue, as shown by the example in this issue.

So here's the situation:

when a lemma is a homonym with multiple lexemes with different meanings sometimes the morphology service (morpheus parser) returns lemmas with a trailing digit to distinguish them.

The lemmas are indexed with these in the short definitions files, so if we get, for example,  οὐδός2, as the lemma from the parser, we can correctly retrieve "way" as the definition for that lexeme, rather than "threshold"

We also have a fallback in the lexicon adapter code, which tells the lookup to try without the trailing digit if the lemma isn't found with it in the index, because these references are specific to the lsj lexicon and likely won't be in other lexical sources.  (e.g. οὐδός could just be indexed once without distinguishing the different lexemes). 

So it's important to keep the digit in the data that is used for looking up in the lexicons, but it not doesn't add any value to the display and it could prevent matching in inflection tables, etc.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I'm going to port this to the incremental release

**Comment by balmas** [comment]
fixed in Alpheios Components 3.3.1-qa.20210108437

**Comment by monzug** [comment]
fixed for οὐδ' in build   Alpheios Reading Tools 3.3.1 build qa.20210108447
Alpheios Components 3.3.1-qa.20210108437 

Unfortunately I could not find any other example to test.

![no-number-greek-popup](https://user-images.githubusercontent.com/41396793/104041182-a6376000-51a6-11eb-8275-64bee75ed439.JPG)

**Comment by balmas** [comment]
this can also be seen often in treebanked text.  e.g. πολλὰς at Odyssey 1.3  (https://texts.alpheios.net/text/urn:cts:greekLit:tlg0012.tlg001.alpheios-text-grc1/passage/1.1-1.30) 

See related item #599

**Comment by monzug** [comment]
Oh yes, thanks. I found plenty of example with numbers in both Latin and Greek but not exactly the same as οὐδ'
