### ISSUE TITLE
lexeme disambiguation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#166]
in Homonym.disambiguate and Lexeme.disambiguate, a lexeme without any inflection data gets added to the Homonym even if the lemmas match.  This should not be the case. If a Lexeme provided as a disambiguator to a Homonym doesn't (1) add any information or (2) disambiguate an existing Lexeme by narrowing its inflections, then it should just be ignored.

test case
https://alpheios-project.github.io/treebank-template/on-the-murder-of-eratosthenes-1-50/1?w=1

περί parse from morph service is

```
{
  "RDF": {
    "Annotation": {
      "about": "urn:TuftsMorphologyService:περί:morpheusgrc",
      "creator": {
        "Agent": {
          "about": "org.perseus:tools:morpheus.v1"
        }
      },
      "created": {
        "$": "2020-02-25T13:52:51.492501"
      },
      "rights": {
        "$": "Morphology provided by Morpheus from the Perseus Digital Library at Tufts University."
      },
      "hasTarget": {
        "Description": {
          "about": "urn:word:περί"
        }
      },
      "title": {},
      "hasBody": {
        "resource": "urn:uuid:idm140705328596168"
      },
      "Body": {
        "about": "urn:uuid:idm140705328596168",
        "type": {
          "resource": "cnt:ContentAsXML"
        },
        "rest": {
          "entry": {
            "uri": null,
            "dict": {
              "hdwd": {
                "lang": "grc",
                "$": "περί"
              },
              "pofs": {
                "order": 6,
                "$": "preposition"
              }
            },
            "infl": {
              "term": {
                "lang": "grc",
                "stem": {
                  "$": "περί"
                }
              },
              "pofs": {
                "order": 6,
                "$": "preposition"
              },
              "stemtype": {
                "$": "prep"
              },
              "morph": {
                "$": "indeclform"
              }
            }
          }
        }
      }
    }
  }
}
```

περί annotation from treebank is:

```
{
  "RDF": {
    "Annotation": {
      "about": "urn:uuid:e3abeaf6-80e9-44a4-9381-820eb56c210e",
      "creator": {
        "Agent": {
          "about": ""
        }
      },
      "created": {
        "$": ""
      },
      "rights": {
        "$": ""
      },
      "hasTarget": {
        "Description": {
          "about": ""
        }
      },
      "hasBody": {
        "resource": "urn:uuid:998987de-846d-4708-9cbc-59ac6dfb562a"
      },
      "Body": {
        "about": "urn:uuid:998987de-846d-4708-9cbc-59ac6dfb562a",
        "type": {
          "resource": "cnt:ContentAsXML"
        },
        "rest": {
          "entry": {
            "dict": {
              "hdwd": {
                "lang": "grc",
                "$": "περί"
              }
            },
            "infl": {
              "pofs": {
                "$": "preposition"
              },
              "term": {
                "form": {
                  "$": "περὶ"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by balmas** [comment]
@kirlat let me know if what needs to be done here isn't clear. thanks.

**Comment by kirlat** [comment]
A small question:
> If a Lexeme provided as a disambiguator to a Homonym ... (2) disambiguate an existing Lexeme by narrowing its inflections, then it should just be ignored.

What does "narrowing its inflections" mean in the context above? Does it refer to a disambiguator that has less inflection items than a disambiguatable homonym (I think probably this is not the case based on the example you've provided in Slack but just want to be sure) or does it refer to a disambiguator that has an inflection with less features than a disambiguatable homonym has?

**Comment by balmas** [comment]
>What does "narrowing its inflections" mean in the context above? Does it refer to a disambiguator that has less inflection items than a disambiguatable homonym (I think probably this is not the case based on the example you've provided in Slack but just want to be sure)

YES, this

**Comment by kirlat** [comment]
Some clarifications on the topic by @balmas (copied from Slack).

A Latin word example: omnia is a homonym with 3 lexemes: an adjective, an adverb and a noun.
The parser gives us all 3 lexemes.
For the noun and adjective it identifies declension
For the adjective it gives us 3 possible inflections
Each inflection has stem, suffix, case number and gender
For the noun it gives us 3 possible inflections
Each inflection has stem + suffix plus case and number
For the adverb it has no inflections

The Treebank gives us a homonym object with just 1 lexeme, the adjective for that lexeme it gives us 1 inflection, with a case=accusative, number=plural and gender=neuter, so if the Homonym from the parse is Homonym A and the Homonym from the Treebank is Homonym B

The resulting Homonym C should have the adjective lexeme identified as the "right" lexeme.
The adjective lexeme should have a declension and just 1 inflection, whose case=accusative, number=plural and gender=neuter a stem and suffix.  This is the superset + most precise information for the lexeme from both Homonym A and B. It should also have a noun lexeme and an adverb lexeme and the data in those lexemes all is what came from Homonym A

That is the SIMPLEST scenario i.e. where we can filter the information provided in Homonym A by a matching Lexeme in Homonym B.

**Comment by kirlat** [comment]
@balmas:
There are all the edge cases too of course, but the general rule to follow is that the homonym that is being used as the "disambiguator" (i.e the one from the treebank) is giving us the most specific and precise information about a word. But it doesn't have all of the information that we can get from the parser.  So we need to combine the information in a way that let's us tell the user "This set of letters forms a word that can be either word A or word B. In this context it is this specific form of word "B".

I think we can assume that disambiguators are more precise but we can't assume whether they are more or less full featured.

**Comment by kirlat** [comment]
@kirlat: need a small clarification
In the example above an info returned from the morphological analyzer for the adjective is:
   for the adjective it gives us 3 possible inflections
   each inflection has stem, suffix, case number and gender
Then for the adjective a treebank:
   it gives us 1 inflection, with a case=accusative, number=plural and gender=neuter
The result:
   the adjective lexeme should have a declension and just 1 inflection, whose case=accusative, number=plural and gender=neuter a stem and suffix. 

I'm wondering why won't it have two other inflections from the morph analyzer? Isn't this the case when we narrow down an information on the lexeme being disambiguated?

@balmas:
Yes it is a case of narrowing down the information, which is why it doesn't have the other 2 inflections. If you think about the problem from the user's perspective they are seeing the word "omnia" used in a specific context. If you lookup the word "omnia" without any context, you can't know whether it is an adjective, noun or adverb, and you can't know which of the possible forms of the adjective or noun it might be. But if you lookup the word "omnia" in a given context, it can only be one of those and it can only have a specific set of grammatically properties.

So for the adjective, without context, it could be one of three cases (e.g. maybe dative, accusative, nominative), but in the given context it can really only be ONE of those -- i.e either it was used in the dative, accusative or nominative. Our parser only knows all the possibilities and nothing about context.

The treebanks are created by somebody (usually an individual, sometimes multiple individuals and an editor) going through and annotating each word in the text to say what it's morpho-syntactic characteristics are in that context. Right now, we have only these 2 options: the parser output, which gives us all possibilities it knows for a word and a treebank, which is an individual person's (or group of people's) opnions about what the "right" information is for that word in that context.

In the future, if we add other more advanced parsers, we could have additional sources of data as well. Any one of these sources could potentially contain information that one of the others doesn't

None are infallible.

Right now, with our current use case, we want to use the data from the treebank, combined with the data from the parser, to show the user all of the possible lexemes for a word that we know about, and if we have a treebank aligned to the word, the specific form of the specific lexeme that was identified by the treebank as the right one. In the future, we might want to do things like allow the user to retrieve results from additional parsers, and use that in a way similar to a treebank or to augment. But that is not the use case we are working on at the moment.

I think what might be confusing you still is the somewhat contradictory position that we want to show all possible lexemes, and for the lexeme that was identified by the treebank as the "right" one, on the very specific form of that lexeme that was identified by the treebank editor. But the questions we are answering for the user are these two things: (1) what are all the words this could be and (2) for the word it really is, how is it being used here.

You might be able to imagine other questions that would be good to answer, that we can't right now with our given resources, but in theory could if we had additional resources.
e.g. (3) what is the most likely way it is being used here
(4) what is the most frequent way it is used
(5) what does this other parser say about all the possible words it could be? Does this other parser know more than the first one?
and so on

But right now, we are focusing on the first 2 questions. The reason the treebank data is both at the same time more precise than the parser output and less complete is that a treebank's purpose is to provide answers to those things that are open for interpretation and not fixed.

So, it's not important to ask a person annotating a treebank what the stem and suffix of the form is, because that information stays the same regardless of what case it is -- i.e. it has a stem and and a suffix and they are the same whether it is nominative or accusative.

The same for the declension. A word belongs to a declension. once you identify the lemma, all forms of that lemma belong to the same declension.

**Comment by balmas** [comment]
Additional test cases for disamiguation

For these test cases:

HomonymA is the base homonym (i.e. result from the parser) and HomonymB is the disambiguator (i.e. result from the treebank)


1. HomonymA contains 1 Lexeme with 3 inflections. HomonymB contains 1 Lexeme with 1 inflection. HomonymA.Lexeme1 matches HomonymBLexeme1 on lemma.word and lemma.part of speech.   HomonymB.Lexeme1.Inflection1 cannot be found in HomonymA.Lexeme1. The resulting Homonym should contain 1 Lexeme with the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymB. Lexeme1 should be flagged as disambiguated

2. HomonymA contains 1 Lexeme with 3 inflections. HomonymB contains 1 Lexeme with 1 inflection. HomonymA.Lexeme1 matches HomonymBLexeme1 on lemma.word and lemma.part of speech.   HomonymB.Lexeme1.Inflection1 matches HomonymA.Lexeme1.Inflection1.  HomonymA.Lexeme1.Inflection1 has a stem and suffix whereas HomonymB.Lexeme1.Inflection1 does not. The resulting Homonym should contain 1 Lexeme with the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymA.Lexeme1.Inflection1 (i.e. the inflection that includes stem+suffix). Lexeme1 should be flagged as disambiguated

3. HomonymA contains 2 Lexemes. HomonymA.Lexeme1  3 inflections. HomonymA.Lexeme2 has 2 inflections. HomonymB contains 1 Lexeme with 1 inflection. HomonymA.Lexeme1 matches HomonymBLexeme1 on lemma.word and lemma.part of speech.   HomonymB.Lexeme1.Inflection1 matches HomonymA.Lexeme1.Inflection1.  HomonymA.Lexeme1.Inflection1 has a stem and suffix whereas HomonymB.Lexeme1.Inflection1 does not. The resulting Homonym should contain 2 Lexemes. Lexeme1 has the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymA.Lexeme1.Inflection1 (i.e. the inflection that includes stem+suffix). Lexeme2 is the exactly the same as HomonymA.Lexeme2. Lexeme1 should be flagged as disambiguated

4. HomonymA contains 2 Lexemes. Homonym B contains 1 Lexeme. HomonymB.Lexeme1 does not match either of the HomonymA Lexemes on lemma.word and lemma.part of speech. The resulting Homonym should contain 3 Lexemes. Lexeme1 should be identical to HomonymB.Lexeme1 except that it should be flagged as disambiguated. Lexemes 2 and 3 should be identical to HomonymA.Lexeme1 and Homonyma.Lexeme2.

5. HomonymA contains 1 Lexeme with 3 inflections. HomonymB contains 1 Lexeme with 1 inflection. the only difference between HomonymA.Lexeme1.lemma and HomonymB.Lexeme1.lemma is that HomonymB.Lexeme1.lemma.word has an initial capital letter.  HomonymB.Lexeme1.Inflection1 matches HomonymA.Lexeme1.Inflection1.  HomonymA.Lexeme1.Inflection1 has a stem and suffix whereas HomonymB.Lexeme1.Inflection1 does not. The resulting Homonym should contain 1 Lexeme. The lemma.word should be the same as HomonymB.lemma (i.e. with initial upper case) and  with the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymA.Lexeme1.Inflection1 (i.e. the inflection that includes stem+suffix). Lexeme1 should be flagged as disambiguated. (see #143)

6. HomonymA contains 1 Lexeme with 3 inflections. HomonymB contains 1 Lexeme with 1 inflection. the only difference between HomonymA.Lexeme1.lemma and HomonymB.Lexeme1.lemma is that HomonymB.Lexeme1.lemma.word uses an alternate encoding for one of its characters (see the language model normalization method for supported alternate encodings).  HomonymB.Lexeme1.Inflection1 matches HomonymA.Lexeme1.Inflection1.  HomonymA.Lexeme1.Inflection1 has a stem and suffix whereas HomonymB.Lexeme1.Inflection1 does not. The resulting Homonym should contain 1 Lexeme. The lemma.word should be the NORMALIZED form of HomonymB.lemma and  with the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymA.Lexeme1.Inflection1 (i.e. the inflection that includes stem+suffix). Lexeme1 should be flagged as disambiguated. (see #143)

7. HomonymA contains 1 Lexeme with 3 inflections. HomonymB contains 1 Lexeme with 1 inflection. the only difference between HomonymA.Lexeme1.lemma and HomonymB.Lexeme1.lemma is that HomonymA.Lexeme1.lemma.word has a trailing digit.  HomonymB.Lexeme1.Inflection1 matches HomonymA.Lexeme1.Inflection1.  HomonymA.Lexeme1.Inflection1 has a stem and suffix whereas HomonymB.Lexeme1.Inflection1 does not. The resulting Homonym should contain 1 Lexeme. The lemma.word should be the form of HomonymA.lemma (the one with the trailing digit) and  with the superset of all attributes from HomonymA.Lexeme1 and HomonymB.Lexeme1 except only the inflection from HomonymA.Lexeme1.Inflection1 (i.e. the inflection that includes stem+suffix). Lexeme1 should be flagged as disambiguated. (see #143)

**Comment by balmas** [comment]
in Alpheios Components 3.3.0-qa.20200410462 but wait on #221 before testing

**Comment by balmas** [comment]
can test in texts-test with Alpheios Components 3.3.0-qa.20200423418

assigning this to myself to test before passing to @monzug

**Comment by balmas** [comment]
@monzug the original issue can be verified with any instance of περί in the treebanked texts (e.g. at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg001.alpheios-text-grc1/passage/878) but more generally, looking at a variety of words in treebanked texts which should be represented as disambiguated and questioning me on any that aren't.

**Comment by balmas** [comment]
Missed a use case here:

HomonymA contains 2 Lexemes. Homonym B contains 1 Lexeme. HomonymB.Lexeme1 matches either of the HomonymA Lexeme1 on lemma.word and lemma.part of speech. Neither Homonym A. Lexeme1 nor HomonymB.Lexeme1 contain any inflection data.  Homonym should contain 2 Lexemes. Lexeme1 should be identical to HomonymA.Lexeme1 except that it should be flagged as disambiguated. Lexeme2 should be identical to HomonymA.Lexeme2.  Essentially what is being disamibugated here is *which* Lexeme is correct.

**Comment by monzug** [comment]
test also the following scenario from #147 :
(1) when the morphology service doesn't produce results -- i.e. in that case the treebank data is the ONLY data. That's the case for φθίνωσιν at https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30

**Comment by kirlat** [comment]
> HomonymA contains 2 Lexemes. Homonym B contains 1 Lexeme. HomonymB.Lexeme1 matches either of the HomonymA Lexeme1 on lemma.word and lemma.part of speech. Neither Homonym A. Lexeme1 nor HomonymB.Lexeme1 contain any inflection data. Homonym should contain 2 Lexemes. Lexeme1 should be identical to HomonymA.Lexeme1 except that it should be flagged as disambiguated. Lexeme2 should be identical to HomonymA.Lexeme2. Essentially what is being disamibugated here is _which_ Lexeme is correct. ( test case for this is https://perseids-publications.github.io/treebank-template/on-the-crown-1-50/4 word παρ᾽)

I've added this case but in my test `παρ᾽` results from morhp analyzer somehow contains two inflections: with `παρά` and `παραί` stems, while results from a treebank has none. According to the logic described above this example should not work because the number of inflections in morph adapter and treebank results do not match. Is that correct?

**Comment by balmas** [comment]
> I've added this case but in my test `παρ᾽` results from morhp analyzer somehow contains two inflections: with `παρά` and `παραί` stems, while results from a treebank has none. According to the logic described above this example should not work because the number of inflections in morph adapter and treebank results do not match. Is that correct?

ah, I think I probably chose the wrong example word for the test case, but actually this one is valid too, so it's a different scenario.

Treebank data can be used to disamibugate a lemma even if it doesn't contain any further inflection data. In the case of παρ᾽, the inflection data provided by the morphological parser is a feature that isn't part of the treebank annotation (dialect). 

Please also note the additional use case from Monica above, about when the treebank provides the *only* data. Here too the lexeme should be marked as disambiguated.

**Comment by kirlat** [comment]
Fixes for the last two cases has been merged to master.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
@balmas, I have a question on this one: let's consider omnia just below mundi origo in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0959.phi006.alpheios-text-lat1/passage/1.1-1.30
1) omnia in treebanking
![omnia-in-diagram](https://user-images.githubusercontent.com/41396793/83893443-eff62e80-a71d-11ea-9424-8b93be44040f.JPG)
2) omnia in lookup
![omnia-lookup](https://user-images.githubusercontent.com/41396793/83893478-fc7a8700-a71d-11ea-8dc6-781a81c97d78.JPG)
in the first omnia pop-up, we are missing that omnia can also be an adj plural nom and voc. because only the acc matches the treebank. so my question is, why don't we include all the data from parser and then add a new entry omnis1 with the treebank flag? if it's a redundant question, pls forgive me...

**Comment by balmas** [comment]
this is a good question. The reason is that when there is a lemma match between the parser and the treebank, we use the treebank to disambiguate the inflection, if we can, so that we can say to the user  it is THIS lemma and THIS case.   We still show the other lemmas because we want to say it could also be these other LEMMAS (and these inflections of these lemmas), but for the one the treebank says it is, we want to show that as specifically as possible.

In addition, we treat a lemma with a trailing 1 as the same as a lemma which matches with everything and has NO digit (but a lemma with a trailing 2 is not the same as a lemma with the same chars but with a trailing 1). This is because our convention is that if we have a homonym with multiple entries in the lexicon, the first one is always represented in our index as both with and without the trailing 1. This is confusing and I wish we could handle it differently but we don't have unique identifiers for lemmas that we can rely upon.

**Comment by monzug** [comment]
I think we have been through this in the past... I take this item back
because I want to be sure to test all the combination.

**Comment by monzug** [comment]
I have tested few combinations such as σύμβολον (I believe scenario 3), then πόντῳ  (HomonymA = Homonym B), then φθίνωσιν, reported above, where the treebank data is the ONLY data.
two questions:
1) in https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30, line 7 - τε  does not have the disambiguated icon nor the treebank icon, why? it should be like καὶ  (line 5)
2) the other one is quemque in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1 (line 35), in whitaker  we have stem 'que' and 'stem 'qu', but we are missing to display the stem 'que' both in lookup and pop-up, then we have quisque from treebank. I am confused on the output of this word. would be qu a packon (whatever packon means) for quisque too? why are we missing 'que' which is in whitaker?

**Comment by balmas** [comment]
> in https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30, line 7 - τε does not have the disambiguated icon nor the treebank icon, why? it should be like καὶ (line 5)

The reason for this is that the treebank does not define at least a lemma and a part of speech for this word, so we cannot disamibugate it.  (But you did actually find a bug in the code here, an error condition wasn't being handled properly. It doesn't change the output, but I will fix the bug.)

**Comment by balmas** [comment]
>the other one is quemque in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1 (line 35), in whitaker we have stem 'que' and 'stem 'qu', but we are missing to display the stem 'que' both in lookup and pop-up, then we have quisque from treebank. I am confused on the output of this word. would be qu a packon (whatever packon means) for quisque too? why are we missing 'que' which is in whitaker (I see a tackon in whitaker????)?

This one is more difficult. The treebank identifies the lemma for this as "quisque1" but the whitaker  parser identifies it as "qu" so we aren't able to match the lemmas. We don't handle the whitaker output very well for this either, it actually returns both a "packon" and a "tackon", and we ignore the tackon piece entirely because it doesn't have a hdwd:


```
    <oac:Body rdf:about="urn:uuid:idm140103424618880">
      <rdf:type rdf:resource="cnt:ContentAsXML"/>
      <cnt:rest xmlns:cnt="http://www.w3.org/2008/content#">
        <entry>
          <infl>
            <term xml:lang="lat">
              <stem>que</stem>
            </term>
            <pofs>tackon</pofs>
          </infl>
          <mean>PACKON w/qui =&gt; whoever it be; whatever; each, each one; everyone, everything;
</mean>
        </entry>
      </cnt:rest>
    </oac:Body>
    <oac:hasBody rdf:resource="urn:uuid:idm140103433679040"/>
    <oac:Body rdf:about="urn:uuid:idm140103433679040">
      <rdf:type rdf:resource="cnt:ContentAsXML"/>
      <cnt:rest xmlns:cnt="http://www.w3.org/2008/content#">
        <entry>
          <infl>
            <term xml:lang="lat">
              <stem>qu</stem>
              <suff>em</suff>
            </term>
            <pofs>pronoun</pofs>
            <decl>1st</decl>
            <case order="4">accusative</case>
            <num>singular</num>
            <gend>masculine</gend>
          </infl>
          <dict>
            <hdwd xml:lang="lat">qu</hdwd>
            <pofs>packon</pofs>
            <freq order="6">very frequent</freq>
          </dict>
          <mean>(w/-que) each, each one; every, everybody, everything (more than 2); whatever;</mean>
          <mean>(w/-que) any; each;</mean>
        </entry>
      </cnt:rest>
    </oac:Body>
```

We get a weird combination of data as a result of the different handling -- We get a nice short definition from Whitaker for 'qu' but no full definition entry. And then if you add the treebank data, we get no short definition for 'quisque' since it didn't match anything Whitaker told us, but we do get a full definition from Lewis and Short.

I am not sure what to do about this. We do already have an issue in the morphsvc for how we mishandle packon/tackon entries: alpheios-project/morphsvc#28. Fixing that wouldn't fully fix this problem. We could change the treebank data to use 'qu' as the lemma to fix this problem for this particular text, although it's likely to come up again for other texts that we don't control if anyone uses this feature.

**Comment by monzug** [comment]
I know I spent sometimes to figure out what was wrong with quemque!
