### ISSUE TITLE
enable configuration of popup size

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#184]
Requested by @vgorman1

One thing that occurs to me as I use Alpheios more and more is that it might be nice if the pop-up box were not so large.  It can easily cover 1/3-1/2 the screen, even if the text size within it is set to small.  It would be nice if it could be resized to be less in the way of the text, so you can see them both without having to resize or drag around  the pop-up box each time you use it.

**Comment by balmas** [comment]
related to this, I was thinking that maybe we should have a default max width on the popup. I think we used to at one point and maybe we lost that with the css changes.

**Comment by kirlat** [comment]
Do we want just to change the default width of the popup so that it will open narrower or do we also want to reduce spacing within the popup itself so that the same amount of text will fit into a smaller popup?

Do we want size settings of a popup to be user configurable?

**Comment by balmas** [comment]
(1) I would like it not to expand to a huge size when there is text that is long.

E.g. look if you open credits for a greek word:
![Screenshot from 2020-04-21 09-37-20](https://user-images.githubusercontent.com/644870/79872378-b8246900-83b3-11ea-926f-ffb241e10020.png)

I am hoping we can set a max width so that it will force the text to wrap properly

**Comment by balmas** [comment]
(2) Yes, I think we want that max size to be user configurable

**Comment by balmas** [comment]
(3) No I don't want to reduce the spacing within the popup itself

**Comment by kirlat** [comment]
Should be solved with #263.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200423418

**Comment by monzug** [comment]
Beautiful. I have a question for @kirlat: how did you come up with the Small and Unrestricted width for the pop-up? I noticed that the Small Option does not correspond to the smallest pop-up when I resize it manually. Is it arbitrary chosen?

**Comment by kirlat** [comment]
> how did you come up with the Small and Unrestricted width for the pop-up? I noticed that the Small Option does not correspond to the smallest pop-up when I resize it manually. Is it arbitrary chosen?

This options restrict the maximum width of a popup with a `max-width` CSS rule (please inspect a popup element with the ID of `alpheios-popup-inner` to see that). The minimal value corresponds to 400px. I've chosen it because, on my opinion, it is the minimal size when popup looks good enough. Then the settings goes with the step of 100px all the way up to 1100px (this is the value right before "unrestricted"). When "unrestricted" value is set, all limitations are cancelled and a popup can be as wide as we want it to. There is no `max-width` CSS rule in this case.

> the pointer in the resizing bar changes appearance when I click on different section in the bar, is there any reason for it

Hmm, I don't see this in my environment. What browser and OS is that? My guess is that it's maybe related to slider being selected (in focus) vs. out of focus. Slider is a system control, and it's appearance is browser/OS dependent: different browsers may draw it differently. So maybe that is the case.

**Comment by monzug** [comment]
it's Chrome on PC. I don't see it in the Mac

**Comment by monzug** [comment]
verified. I don't see any issue. here. Thanks @kirlat for the answers.
