### ISSUE TITLE
realign Change to with Page language dropdown in pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#259]
this is in Chrome on Mac
see attachment
![Screen Shot 2020-04-22 at 2 19 23 PM](https://user-images.githubusercontent.com/41396793/79981144-745d5c80-84a4-11ea-8167-da26d19baa70.png)

**Comment by kirlat** [comment]
This happens because, when a popup is narrower, a label appears on top of the control, and the top of the text at the left is aligned with the label:
![image](https://user-images.githubusercontent.com/18631055/81049757-df108e00-8ecf-11ea-8c70-f0e4847cbedd.png)

When the pop becomes wider, the label slides to the left of the control, and the result is not so pretty.

As we cannot satisfy both into going to great lengths with JS or something of the same level, the most effective solution, on my opinion, is to keep label on top even if the popup is wide:
![image](https://user-images.githubusercontent.com/18631055/81049993-56462200-8ed0-11ea-983d-15b1385eb0cd.png)

It adds a couple of pixels of extra height, but looks better, on my subjective opinion. I also think we should not care about this extra height too much: those messages are for emergency situations only, they are not there to be displayed all the time. They are to attract attention (greater height attracts more attention too!) and make user react. Once a user responded to the notification, it will be closed for a while, at least.

Please let me know what do you think. If you'll approve, I will submit a PR for this. Thanks!

**Comment by balmas** [comment]
that works for me.

**Comment by kirlat** [comment]
Has been merged to master.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200507327

**Comment by monzug** [comment]
@balmas:  I can't remember when page language was introduced. do you? I search on GitHub with no luck.
still it looks funny -> Change to:  Page language:

![page-language](https://user-images.githubusercontent.com/41396793/81956956-f3444180-95d9-11ea-8c04-fb0d50f123d3.JPG)

**Comment by balmas** [comment]
I'm not sure but I agree it's not looking great.
I wonder if we even need to have the label there. Maybe we could just drop it. What do you think @monzug ?

**Comment by monzug** [comment]
I was comparing with texts.alpheios.net and the look is sleeker there

**Comment by balmas** [comment]
I think we should just remove the Page Language caption in the notification lookup box.

**Comment by kirlat** [comment]
Changes that remove a "Page Language" label have been merged to master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
page language has been removed

![Screen Shot 2020-05-28 at 2 58 31 PM](https://user-images.githubusercontent.com/41396793/83144588-db011600-a0f3-11ea-9241-58e69f09f13b.png)
