### ISSUE TITLE
Mouseover still works even if not longer checked

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#292]
I just logged in to a session that I used for testing the mouse over and Chinese the day before. Even if the mouse over event is not checked in Options, I am still able to mouse over on greek words and generate the pop-up. this is in Loeb classics
see attachment
![mouseover-loeb](https://user-images.githubusercontent.com/41396793/80809456-b581fa80-8b8f-11ea-8444-315e797910ae.JPG)

**Comment by balmas** [comment]
something is weird with the color of that "Don't Ask Again" button too...

**Comment by monzug** [comment]
I think I enter an issue about Loeb classics

**Comment by monzug** [comment]
https://github.com/alpheios-project/alpheios-core/issues/251

**Comment by irina060981** [comment]
>I just logged in to a session that I used for testing the mouse over and Chinese the day before. Even if the mouse over event is not checked in Options

@balmas, I found the problem, but it is an old code and I am not sure what is the purpose of such restrictions. I would describe, may be you help me with it.

The problem here is - that when we upload the setting `enableMouseMove` and it is true, it would be alway overwritten inside setting component to false.
This way we see it as unchecked because of `selectedOverride` , that is always fase on the start:

first we define `selectedOverride` inside `feature-settings.vue` this way:
```
mouseMoveChecked: function() {
   return this.app.getMouseMoveOverride() ? 'true' : 'false'
},
```

so it is alway a string, and on startup it is false, I believe because it shouldn't override anything
and then in settings we always get false settings without any depending on the current uploaded value for the user

```
if (typeof this.selectedOverride === 'string') {
          if (this.dataModel.boolean == true) {
            rv = this.selectedOverried === 'true'
          } else {
            rv = this.selectedOverride
          }
        }
```

**Comment by irina060981** [comment]
@balmas , what was the purpose of such code? do you remember?

**Comment by balmas** [comment]
I added it in this PR https://github.com/alpheios-project/components/pull/897

It was to enable this functionality:

>This PR changes the way the mousemove word selection event works:
when enabled, it applies to the entire page, not just Chinese
when enabled, the regular word lookup trigger event is deactivated
the client of components (e.g. the embedded library) can override the default setting for the mousemove event and turn it on by default for the page (user can subsequently override)

**Comment by balmas** [comment]
The point was to make sure that on a page using the embedded library where mousemove was enforced over options and where the page had both chinese and non-chinese text, lookup behavior was consistent for all languages.

But it should not apply to other pages accessed via the webextension only when mousemove is enforced by the embedded library setting.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200507327

**Comment by monzug** [comment]
tested in Chrome (loeb and latin library) and FF (Loeb) - works perfectly.
