### ISSUE TITLE
problem with selecting current language

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#346]
When I select  page language Syriac in pop-up, the field is not updated and is empty.
see screenshot
![aramaico](https://user-images.githubusercontent.com/41396793/82228196-d28c2c80-98f6-11ea-8794-5792dc55769c.JPG)

**Comment by monzug** [comment]
Actually it's true for all the experimental languages

**Comment by balmas** [comment]
I probably broke this then.

**Comment by monzug** [comment]
should be an easy fix, right?

**Comment by balmas** [comment]
yes I hope so :-)

**Comment by monzug** [comment]
actually, I have a question here. if I double click on desiderat.  it takes also the dot as the page language is syriac. interesting, in the wordlist it's displayed with the dot first. see wordlist

![desiderat](https://user-images.githubusercontent.com/41396793/82230243-7676d780-98f9-11ea-87ef-7a74c35a0e7d.JPG)

**Comment by balmas** [comment]
that's interesting. I think actually the punctuation list for Syriac might be wrong ...  I think I just copied the one from the Ge'ez language model . Let's add this as a new issue for me to investigate.

**Comment by balmas** [comment]
the problem reported in this issue occurs because of a mismatch between the values in the model object for the setting component and the values in the uiController.languageNames constant

We try to determine the selected item by passing the value of state.app.currentLanguageName, and that's set as the value from uiController.languageNames 

This is all a bit of a mess.

**Comment by balmas** [comment]
The issue here is two fold:
1) we add the "Experimental" in the dropdown so that the user can see that the language is experimental when they choose to use it, but we don't want to include that "Experimental" text everywhere else in the UI we refer to it by name (such as in the notification messages when a word isn't found, in the wordlist, etc.)

2) Really we should have a single source of truth for language names  and not have these repeated in various places in the code

I'm not going to try to tackle the 2nd issue right now. For the first, I think the best solution is to get rid of the words "(Experimental) from the language selection dropdowns and instead just issue a notification when the user selects one of these languages so that they will be informed at that time that they are experimental.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200522457

**Comment by monzug** [comment]
experimental has been removed next to chinese and syriac languages, so the page language field is populated corrcetly
