### ISSUE TITLE
wordlist is different when login from different sites

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#349]
related to issue #291 ?
I do login as user Test@test.it for testing (whatelse could I do with such username???)
anyhow, first my long wordlist as user Test was gone.
second, I did notice that when I log in at http://sedra.bethmardutho.org/library, the wordlist has a combination of latin and Syriac words saved, but when I log off and then in again in latinlibrary as same user Test, the wordlist is totally different. it's a combination of Latin and greek words. Sometimes, I log in and there is no wordlist saved. 

see screenshots of two different wordlist for same user Test

![lat-greek-wordlist](https://user-images.githubusercontent.com/41396793/82237764-2fdaaa80-9904-11ea-95ff-888f44f87f55.JPG)

![loading-wordlist](https://user-images.githubusercontent.com/41396793/82237817-4123b700-9904-11ea-9718-7251edaa15c0.JPG)

**Comment by monzug** [comment]
interesting. I reinstalled the release and logged in as user Test and my old LOOOONG wordlist is there.

**Comment by balmas** [comment]
@monzug the difference could be whether or not you are pointing at the dev user word api or not via the env-webext.js

These are two different databases now in the production and dev environments.

**Comment by monzug** [comment]
good to know that my beautiful wordlist is still there. glad you pointed that out. anyhow, there is still the difference between sites  with same env-webext.js.

**Comment by irina060981** [comment]
if to be honest I saw such strange changes with wordLists with testUser
but I thought that it was because we could both use test account at the same time

will try to reproduce again

**Comment by monzug** [comment]
Thanks

**Comment by irina060981** [comment]
I tried to use testUser account and 2 my personal accounts
in Chrome and Firefox
in various sequence
the problem was not reproduced

I think we couldn't catch such a problem on the client side
because client sends the same request to remote
and if the problem is still reproducable, then remote should return different results for the same api request
so I think that we should create some check on the server side
because if such a problem is actual - it could really create problems for our users

@balmas, what do you  think about such an approach?

**Comment by balmas** [comment]
@irina060981 what is the scenario the server should catch exactly?

**Comment by irina060981** [comment]
I mean the folowing:

we are sending the following api

GET userapis.alpheios.net/v1/words/?languageCode=lat
and in authorization we hide user details

I could see two potential problems for the described scenario here:
 - server converts user details not correctly sometimes
 or
- different server instances could return different copy of database

if the problem is reproducable rarely, than it could be the second variant
on different balancing conditions we could have different results  (in theory of course)

so we could create a user,
create the first list of words and pull it to remote

wait several days
and change the list of words

wait several days
and change again

and then we could create a scheduled check every day - if the api returns the same list as we got after the last changes

and if it would be the same during a month for example, we could be more sure - that the server is ok

and then we should wait for another feedback that some user lost his words 

@balmas , what do you think?

**Comment by balmas** [comment]
Hmm. I don't think the server could be converting the user details incorrectly. The user id is in an encrypted token and there isn't really anyway it could be getting it wrong.

Here are the variables in this situation:

1 test account id
2 different remote dbs (dev and prod)
2 different users of the test id (you and Monica)
2 (or more) different local browser caches of the test account words

When we login to a user account, we do the following:

1. retrieve wordlist items from the remote db
2. merge them with the local cached list
3. delete any local items that didn't exist in the remote db

So with you and Monica both using the same id, sometimes with the remote dev db and sometimes with the remote prod db there are many opportunities for the wordlist data to get crossed

I think ideally, we would have a check to make sure that a local list a remote list are at least using the same source db (dev or prod).  However, I'm not sure this is a real user scenario for us right now so I'm a little dubious of the urgency.

**Comment by irina060981** [comment]
yes, while we couldn't define the stable scenario for this - 
and my cases (that were not only with test user, I believe, but I am not sure - because it is really not easy to catch while you don't choose words to wordlist with attention) are not repeated and could be because of not updated environment

**Comment by irina060981** [comment]
@balmas and @monzug , so may be postpone this case before would have some similiar cases in future?

**Comment by monzug** [comment]
I'll take it. I will do some testing during regression to see if it's
reproducible. can you assign pls?

**Comment by monzug** [comment]
uhm, I am trying to reproduce this scenario, but I got this wordlist with syriac words. do I still need to point to a dev database?

![Screen Shot 2020-05-29 at 3 20 26 PM](https://user-images.githubusercontent.com/41396793/83264267-21bc4200-a1c0-11ea-9754-6ccee48ddf2f.png)

**Comment by balmas** [comment]
yes you do still need the dev database. I think I should probably plan to deploy the new schema to the prod database soon. It shouldn't do any harm, but I don't want to do it on a Friday so I will plan to on this coming Monday.

I don't think that should be creating the character display issue though... not sure what is happening there.

**Comment by monzug** [comment]
I haven't been using the dev database since I installed this latest build yesterday.

**Comment by balmas** [comment]
hmm. then I would guess your new lookups can't be saved to the wordlist

**Comment by monzug** [comment]
only the lookups or also double clicking?  because I see the latest been
saved

**Comment by balmas** [comment]
are you definitely not using the dev database? I would expect saves of new lookups to fail if you are.

**Comment by monzug** [comment]
let me check

**Comment by monzug** [comment]
I was not using the dev database. I am going to update the file now. is
there anything that I need to retest because affected by using the regular
database?

**Comment by balmas** [comment]
Only wordlist related items.

**Comment by monzug** [comment]
ok

**Comment by monzug** [comment]
and this is when I log in to latin library as test-monica. 

![Screen Shot 2020-05-29 at 4 56 43 PM](https://user-images.githubusercontent.com/41396793/83273984-74e8c180-a1cd-11ea-9fcc-b6c500cf8b80.png)

**Comment by balmas** [comment]
hmm. it looks to me like maybe nothing is actually getting saved to the db. 

Can you check the debug console to see if there are any errors?

**Comment by balmas** [comment]
@monzug I think this is my fault, I forgot to tell you to also change the audience in the env-webext.js file
you should have

```
ENDPOINTS: {
    'wordlist' : 'https://userapis-dev.alpheios.net/v1/words',
    'settings' : 'https://settings.alpheios.net/v1/settings'
  },
  AUDIENCE: 'alpheios.net:dev-apis',
```

can you check that?

**Comment by balmas** [comment]
@monzug I have deployed the schema change to the production environment now, so you should be able to test fully using the prod environment only.

**Comment by monzug** [comment]
I was just changing the env file right now. excellent. Thanks

**Comment by monzug** [comment]
retested with the updated environment and I could not reproduce this scenario. I am  going to close this one. will enter a new issue for the character dislay
