### ISSUE TITLE
problem with treebank attributes when target and selected word don't match

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#383]
When I select words quickly in sequence on the Odyssey page, sometimes the target of the htmlSelector that gets passed to `TreebankDataItem.getTreebankData` (on line 467 of lexis.js where we create the lexicalQuery) is the entire parent div of the line, rather than span containing the selected word.  In this case, the TreebankDataItem.getTreebankData call returns null, because it's not finding the data attributes on the target element.  The word ends up getting selected correctly, so apparently this is a case where our word selection logic is on the one hand, doing the right thing, by finding the text of the word and updating the range, but unfortunately the target we're relying on for the treebank info is still the target of the parent element.

**Comment by kirlat** [comment]
I've tried to reproduce it, and I was able to, but probably in a slightly different way. No matter how fast I clicked on the words, I was not able to get a treebank work incorrectly. But if I clicked between the words, within a space, then selection did span over the whole line, even though there is a meaningful word in a popup shwon. In that case treebank gets stuck and is not showing any more, even if selection is right the next time.

I think that in order to solve this we probably have to fine tune a selection algorithm (I wish it was not so!), because it seems we do not adjust a selection correctly when it is between the words. And we also should improve a treebank's error handling. Do you agree?

Do you think the issue you've described is similar to what I've found or is it a different one?

**Comment by balmas** [comment]
>if I clicked between the words, within a space, then selection did span over the whole line, even though there is a meaningful word in a popup shwon. In that case treebank gets stuck and is not showing any more, even if selection is right the next time.

Yes and regardless if we fix the selection problem, that is a flaw in the treebank failed logic that definitely needs to be fixed as described at https://github.com/alpheios-project/alpheios-core/issues/258#issuecomment-634119573

**Comment by balmas** [comment]
>Do you think the issue you've described is similar to what I've found or is it a different one?

Yes, it could be that it's less about speed than exactly where we click.  I'm less certain we should try to fix this right now, particularly since we can transition the way the treebank texts are marked up to use the new sentence level alignment which should make this much less of an issue for us.

**Comment by kirlat** [comment]
A fix is merged to master.

**Comment by balmas** [comment]
Alpheios Components 3.3.0-qa.20200527404

**Comment by monzug** [comment]
I am still able to reproduce the selection of few lines  over a specific word. it does happen when the word is close to the bottom of the page. basically the selection shift below the selected word and stop few lines lower than the specific word and the morphology lookup and the treebank are generated based on the last word highlighted. it's an edgy case.

**Comment by balmas** [comment]
Agree it's an edge case. I think we can mitigate it after the release by improving the markup of our treebanked texts to use sentence level alignment rather than word level, eliminating the spans around each word.  I'll create a new issue for that.

**Comment by balmas** [comment]
I'm closing this one.
