### ISSUE TITLE
enableMouseMove is not working anymore

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#400]
In
Alpheios Reading Tools 3.1.0 build qa.20200527411
Alpheios Components 3.3.0-qa.20200527404

I have useMouseOverToSelectWords checked in options but there is no response to mouse movements.

I think it might have been broken by the changes in #375

**Comment by balmas** [comment]
@kirlat see 
https://github.com/alpheios-project/alpheios-core/commit/9fea9dbef9d72e93ef9b3bdf60c09ffc26024a67#r39529571

I think this line was needed because of the following:

upon init we call registerGetSelectedText which registers the regular default listener (i.e. double-click) but does not check whether that should be overridden by the mousemove listener

Upon activation of Alpheios (i.e. in activate() method of UIController), we activate all listeners, but we don't end up activating a mousemove listener because it wasn't registered

I think code that was there was a bit of a workaround though, and might have caused other problems because we didn't really want to activate the listener until the tools are enabled.

What we probably really want to do is register both listeners upon init, but only activate one or the other at the time of activation.

**Comment by monzug** [comment]
Mousemove works for me in chinese site https://ctext.org/

**Comment by balmas** [comment]
it depends upon when and how it is activated. if you change it from double-click to mousemove after loading the page it should work. But if it's already at mousemove when you load the page it probably will not.

**Comment by monzug** [comment]
interesting

**Comment by balmas** [comment]
@kirlat FYI I will take this one and work on it today.

**Comment by kirlat** [comment]
> @kirlat FYI I will take this one and work on it today.

Thanks!

**Comment by kirlat** [comment]
> What we probably really want to do is register both listeners upon init, but only activate one or the other at the time of activation.

I think this is how it should work ideally, and this is an intended use. Why we have many register/deregister calls with mousemove is probably because it has variable options such as precision and delay. That's why we recreate it every time it's activated: to be sure that a (potentially) changed parameters are passed to the event's constructor.

I think the best approach would be to change an API of a `UIEventController` so that we will be able to change options of any registered event without deregistering and re-registering it. It should not be hard, but probably it will still be a too risky change before the release; it's probably safer to put a deleted code back. But in the future it would maybe be good to do this change because, as is, mousemove registration and activation logic is a little bit more complex than it should be, on my opinion.

What do you think?

**Comment by balmas** [comment]
>I think the best approach would be to change an API of a UIEventController so that we will be able to change options of any registered event without deregistering and re-registering it. It should not be hard, but probably it will still be a too risky change before the release; it's probably safer to put a deleted code back. But in the future it would maybe be good to do this change because, as is, mousemove registration and activation logic is a little bit more complex than it should be, on my opinion.

I am not sure. I agree it's not the time to do refactoring right now, but I think the main problem with the mousemove event is that it wasn't handled as just another valid value for the textQueryTriggerDesktop option. I think initially there was some confusion about how it should be implemented - i.e. it was done first only for chinese, and when I decided it should apply to all languages, it should probably have been refactored then.

**Comment by monzug** [comment]
it works fine. tested in FF/PC and Chrome/Mac
