### ISSUE TITLE
Error when clicking on Packon from pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#438]
If I click on packon from morphology pop-up ( see word quemque in https://texts-test.alpheios.net/text/urn:cts:latinLit:phi0620.phi001.alpheios-text-lat1/passage/1.1  line 35)
on Safari, I get an error (see screenshot) while in Chrome/PC it keeps loading the empty page (see screenshot with the console log)

![Screen Shot 2020-06-09 at 4 23 01 PM](https://user-images.githubusercontent.com/41396793/84160479-83a56300-aa6e-11ea-8b10-fbe85721b63f.png)

console log (Chrome)

![log-error](https://user-images.githubusercontent.com/41396793/84160586-5770ee80-aa3c-11ea-8898-ba144f05f396.JPG)

**Comment by balmas** [comment]
nice catch! This was happening because a pofs entry for packon is not found in the index and the default in that case is to use the entry for alph-general-index, but that was not right in the index file. It was empty and instead needed to be set to index.htm

This is fixed in the live allen-greenough-index file now. You'll probably need to clear your cache to get the updated file.
