### ISSUE TITLE
something about the latest core code breaks the ff webextension

### ISSUE THREAD

**Issue by balmas** [alpheios-project/alpheios-core#549]
not sure what the source of this is exactly but when the webextension is built with the master branch of alpheios-core, activation fails to add the alpheios elements to the page.  Reverting to the production branch of alpheios-core works fine so it is not a problem with the webextension code.

The core code does work under Firefox with the embedded library.

I suspect it might be a problem in the webpack build of content.js somehow but cannot isolate it.

**Comment by kirlat** [comment]
The problem seems to be with the `symbol-observable` package, a dependency of the Apollo client. In a webextension environment the following line fails: https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js#L13. It produces an unhandled exception (`Symbol.for` is not defined) and that prevents content script from loading.

The interesting thing is that the package uses not `Symbol.for` but `self.Symbol.for` (see https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js#L3, the `root` in case of a webextension is `self`) and that somehow fails.

If to put a try/catch block around the line 13 (https://github.com/benlesh/symbol-observable/blob/master/es/ponyfill.js#L13), it solves the issue and the webextension is loading and functioning properly. But that means we'll need to patch the file.

I'll try to go deeper into this and see if there is a more elegant solution to the issue.

**Comment by kirlat** [comment]
I've added an issue to both the `symbol-observable` (benlesh/symbol-observable/issues/53) and to the Firefox bug tracker as it seems to be a Firefox issue (it does not occur in Chrome): https://bugzilla.mozilla.org/show_bug.cgi?id=1675725

**Comment by balmas** [comment]
thanks for tracking this down.  If we can implement the patch easily I'd suggest we do that for now and wait and see if either the issue on symbol-observable or Firefox get action

**Comment by kirlat** [comment]
I think I've found a simple solution that should fix it without the need for patching. Will submit it soon.

**Comment by kirlat** [comment]
This should be fixed by  alpheios-project/webextension#314

**Comment by balmas** [comment]
@monzug you should be able to regress in FF now with the dev build at https://github.com/alpheios-project/webextension/releases/download/dev.20201109457/dist.zip

**Comment by monzug** [comment]
Great.

**Comment by monzug** [comment]
toolbar is there on FF/PC in  Alpheios Reading Tools 3.3.2 build dev.20201109457
Alpheios Components 3.3.1-dev.20201109442 build dev.20201109298
