### ISSUE TITLE
Greek demonstrative and interrogative pronoun tables missing in Browse Inflection tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alpheios-core#622]
we are not showing the demonstrative and interrogative pronoun tables in Browse inflection tables.  I can actually match to those tables with οὗτος  or  τίνοιν
this is in the release Alpheios Embedded Library 3.3.1-20200821383
Alpheios Components 3.3.1-20200821376       and in   Alpheios Embedded Library 3.3.1-20200821383
Alpheios Components 3.3.3-qa.20210119683

**Comment by irina060981** [comment]
After 3 days of searching, digging inside inflection tables code, a lot of experiments - I found the problem.
There were defined not appropriate pronouns for these views in inflection browser.

I changed 
**Demonstrative Pronoun Declension** - was `τούτω` - now `οὗτος`
**Interrogative Pronoun Declension** - was `τίνε` - now `τίς`

And now it works

**Comment by irina060981** [comment]
I will leave some notes here:
- the source failed check was - `GreekPronounView.getMorphemes` failed because inflectionData does not have any types
- pronoun inflection was defined as suffixBased (instead of formBased), so it doesn't find appropriate types - `LanguageDataset.setInflectionData -> hasMatchingForms for fullFormBased`
- the problem of wrong definition was in the homonym that is used as standard for a inflection table in inflection browser - `GreekPronounView.createStandardFormHomonym`
- it was failed on pronoun class definition (it is an obligatory match condition) - `GreekLanguageModel.getPronounClasses`
- It couldn't define class for pronoun because in the saved forms (`greek/data/pronoun/forms.csv`) given words has different hdwd

So finally - I changed given forms in homonym examples (components -> vue -> inflections-browser-tables.json) to its hdwd - and tables became renderable

**Comment by irina060981** [comment]
@monzug, I will prepare extension for testing in Forefox tomorrow.
It will have this change and turned off permisions (as we decided on the meeting).

**Comment by monzug** [comment]
where can I download the webextension from, when ready?

**Comment by irina060981** [comment]
For now it is not ready, because as I wrote in letters we could not simply remove access permissions.
When it would be solved - it would be here - https://github.com/alpheios-project/webextension/releases

It is already there - but not working properly

**Comment by monzug** [comment]
Thanks!!!

**Comment by monzug** [comment]
I did install the latest FF build by copying the dist folder over an old build that I have been using since nov 2019.
I can browse the greek pronoun tables now. However I keep getting an error: lexical data is loading from lookup and double click but not from wordlist. see below some errors that I see in the browser console. it might be my environment in which case I will be happy to start build from scratch.
![Screen Shot 2021-11-17 at 1 28 31 PM](https://user-images.githubusercontent.com/41396793/142202699-4da58eec-4c18-4044-a262-866268c34078.png)
![Screen Shot 2021-11-17 at 1 19 16 PM](https://user-images.githubusercontent.com/41396793/142202702-8f958eb3-cacb-4ba7-a9e6-e76d4b1fd9f2.png)
![Screen Shot 2021-11-17 at 1 09 35 PM](https://user-images.githubusercontent.com/41396793/142202704-e4f823ce-d305-4778-9a63-8abaa2f5de06.png)

**Comment by irina060981** [comment]
Both errors are not related to my changes.
Let's move them to separate issues.

**Comment by irina060981** [comment]
I think this issue could be closed

**Comment by monzug** [comment]
tested in build
to be retested in Chrome, PC and MAC and  Safari/MAC

**Comment by monzug** [comment]
Chrome looks good too
